name: FPL Data Update

permissions:
  contents: write

on:
  schedule:
    # NOTE: GitHub Actions uses UTC. Times below are set for SGT (UTC+8).
    - cron: "0 14 * * *" # Daily at 22:00 SGT (14:00 UTC)
    - cron: "0 12 * * 2" # Weekly on Tuesday at 20:00 SGT (12:00 UTC)
  workflow_dispatch: # Manual trigger

jobs:
  update-fpl-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run FPL update
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scripts/export_data.py
