name: FPL Data Update

on:
  schedule:
    - cron: '0 6 * * *'    # Daily at 6:00 UTC - Essential data only
    - cron: '0 18 * * 2'   # Weekly on Tuesday at 18:00 UTC - Full update
  workflow_dispatch:        # Manual trigger

jobs:
  update-fpl-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install pandas numpy supabase python-dotenv requests
          
      - name: Run FPL update
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scripts/export_data.py
        
      - name: Commit and push changes (Data Export)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update FPL data $(date +'%Y-%m-%d %H:%M UTC')" && git push)